import { StyleSheet, Platform } from 'react-native';
import { Typography } from '../../constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0D0D0D',
  },
  keyboardAvoid: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderColor: '#1F1F1F',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2,
    fontFamily: Typography.fontFamily,
  },
  indicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#333333',
    marginLeft: 6,
  },
  activeDot: {
    backgroundColor: '#FFFFFF',
    transform: [{ scale: 1.3 }],
  },
  completedDot: {
    backgroundColor: '#666666',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
  },
  stepContainer: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 24,
    paddingBottom: 24,
  },
  scrollStep: {
    flex: 1,
    paddingTop: 24,
  },
  scrollStepContent: {
    paddingBottom: 48,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 16,
    fontFamily: Typography.fontFamily,
  },
  subtitle: {
    color: '#888888',
    fontSize: 14,
    marginBottom: 24,
    fontFamily: Typography.fontFamily,
  },
  body: {
    color: '#CCCCCC',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 16,
    fontFamily: Typography.fontFamily,
  },
  boldText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: Typography.fontFamily,
  },
  diagramContainer: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#222222',
    borderRadius: 8,
    padding: 16,
    marginVertical: 24,
  },
  diagramText: {
    color: '#888888',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: Typography.fontFamily,
  },
  diagramTimeline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timelinePoint: {
    alignItems: 'center',
    flex: 1,
  },
  timelineLabel: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: Typography.fontFamily,
  },
  timelineSub: {
    color: '#666666',
    fontSize: 8,
    marginTop: 4,
    textAlign: 'center',
    fontFamily: Typography.fontFamily,
  },
  timelineBar: {
    width: 20,
    height: 1,
    backgroundColor: '#333333',
    marginHorizontal: 4,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    color: '#AAAAAA',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
    fontFamily: Typography.fontFamily,
  },
  textInput: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderRadius: 6,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: Typography.fontFamily,
  },
  helperText: {
    color: '#555555',
    fontSize: 12,
    marginTop: 4,
    fontFamily: Typography.fontFamily,
  },
  summaryPanel: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderRadius: 8,
    padding: 16,
    marginTop: 8,
    marginBottom: 24,
  },
  summaryTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 8,
    letterSpacing: 0.5,
    fontFamily: Typography.fontFamily,
  },
  summaryText: {
    color: '#BBBBBB',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Typography.fontFamily,
  },
  summaryCalc: {
    color: '#888888',
    fontSize: 12,
    marginTop: 8,
    borderTopWidth: 1,
    borderColor: '#222222',
    paddingTop: 8,
    fontFamily: Typography.fontFamily,
  },
  highlightText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
  permissionStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141414',
    borderRadius: 8,
    padding: 16,
    marginVertical: 40,
    borderWidth: 1,
    borderColor: '#222222',
  },
  permissionStatusLabel: {
    color: '#888888',
    fontSize: 14,
    marginRight: 8,
    fontFamily: Typography.fontFamily,
  },
  permissionStatus: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: Typography.fontFamily,
  },
  activeText: {
    color: '#FFFFFF',
    fontFamily: Typography.fontFamily,
  },
  inactiveText: {
    color: '#E74C3C',
    fontFamily: Typography.fontFamily,
  },
  searchInput: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#222222',
    borderRadius: 6,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 16,
    fontFamily: Typography.fontFamily,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#666666',
    fontSize: 12,
    marginTop: 12,
    fontFamily: Typography.fontFamily,
  },
  appList: {
    flex: 1,
    marginBottom: 20,
  },
  appListContent: {
    paddingBottom: 16,
  },
  appRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#1C1C1C',
    borderRadius: 6,
    marginBottom: 8,
  },
  appRowActive: {
    borderColor: '#333333',
  },
  appInfo: {
    flex: 1,
    marginRight: 16,
  },
  appName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
  appPkg: {
    color: '#555555',
    fontSize: 11,
    marginTop: 2,
    fontFamily: Typography.fontFamily,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: '#444444',
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  checkMark: {
    color: '#000000',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: Typography.fontFamily,
  },
  primaryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#000000',
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: Typography.fontFamily,
  },
  primaryButtonDisabled: {
    backgroundColor: '#333',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#333333',
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
  textInputDisabled: {
    backgroundColor: '#0F0F0F',
    borderColor: '#181818',
    color: '#555555',
    fontFamily: Typography.fontFamily,
  },
  presetContainer: {
    flexDirection: 'row',
    backgroundColor: '#141414',
    borderRadius: 8,
    padding: 4,
    borderWidth: 1,
    borderColor: '#222222',
    marginBottom: 16,
    marginTop: 10,
  },
  presetTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 6,
  },
  presetTabActive: {
    backgroundColor: '#FFFFFF',
  },
  presetTabDisabled: {
    opacity: 0.4,
  },
  presetTabText: {
    color: '#888888',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
  presetTabTextActive: {
    color: '#000000',
    fontWeight: 'bold',
    fontFamily: Typography.fontFamily,
  },
  presetTabTextDisabled: {
    color: '#555555',
    fontFamily: Typography.fontFamily,
  },
  presetDescPanel: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#222222',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  presetDescTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 6,
    fontFamily: Typography.fontFamily,
  },
  presetDescText: {
    color: '#888888',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: Typography.fontFamily,
  },
  disclosureContainer: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#333333',
    borderRadius: 8,
    padding: 16,
    marginVertical: 20,
  },
  disclosureTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    textTransform: 'uppercase',
    fontFamily: Typography.fontFamily,
  },
  disclosureText: {
    color: '#CCCCCC',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: Typography.fontFamily,
  },
  consentCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingVertical: 8,
  },
  consentText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 12,
    fontFamily: Typography.fontFamily,
  },
  createdGroupsContainer: {
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#262626',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  createdGroupsHeader: {
    color: '#888888',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 8,
    fontFamily: Typography.fontFamily,
  },
  createdGroupRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderColor: '#1C1C1C',
  },
  createdGroupName: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: Typography.fontFamily,
  },
  createdGroupCount: {
    color: '#888888',
    fontSize: 11,
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
});

